export const APP_ERROR_CODES = [
    "UNKNOWN_ERROR",
    "REPOSITORY_ERROR",
    "INVENTORY_UNAVAILABLE",
    "INVALID_INVENTORY_DATA",
    "CONFIGURATION_ERROR",
    "GOOGLE_SHEETS_CONFIGURATION_ERROR",
    "GOOGLE_SHEETS_AUTHENTICATION_ERROR",
    "GOOGLE_SHEETS_UNAVAILABLE_ERROR",
    "GOOGLE_SHEETS_READ_ERROR",
    "GOOGLE_SHEETS_MAPPING_ERROR",
] as const;

export type AppErrorCode = (typeof APP_ERROR_CODES)[number];
